# Generated by Django 5.1.6 on 2025-02-25 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
        ('products', '0002_remove_product_price_productprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='field',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='form',
            name='head_text',
            field=models.TextField(default='Please fill out the form below'),
        ),
        migrations.AddField(
            model_name='form',
            name='product_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='products.product'),
        ),
        migrations.AddField(
            model_name='form',
            name='subheader_text',
            field=models.TextField(default='All fields marked with * are required'),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('email', 'Email'), ('phone', 'Phone'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('select', 'Select')], max_length=50),
        ),
    ]
