# Generated by Django 5.1.6 on 2025-02-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_field_is_required_field_is_visible_form_head_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='placeholder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
