# Generated by Django 5.1.6 on 2025-03-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_unique_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='unique_ids',
        ),
        migrations.AddField(
            model_name='order',
            name='unique_id',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True, unique=True),
        ),
    ]
