# Generated by Django 5.1.6 on 2025-03-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_unique_ids_order_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='unique_id',
            field=models.CharField(editable=False, max_length=12, unique=True),
        ),
    ]
